name: Deploy Cloud Function

on:
  push:
    branches:
      - main  # Adjust to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FIREBASE_SDK_TYPE: ${{ secrets.FIREBASE_SDK_TYPE }}
      TEST_SECRET: ${{ secrets.TEST_SECRET }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          service_account_key: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      - name: Set up Environment Variables
        run: |
          echo "FIREBASE_SDK_TYPE=${FIREBASE_SDK_TYPE}" >> $GITHUB_ENV
          echo "TEST_SECRET=${TEST_SECRET}" >> $GITHUB_ENV

      - name: Deploy Cloud Functions
        run: |
          ENV_VARS_LIST="FIREBASE_SDK_AUTH_URI,FIREBASE_SDK_CLIENT_EMAIL,FIREBASE_SDK_CLIENT_ID,FIREBASE_SDK_CLIENT_X509_CERT_URL,FIREBASE_SDK_PRIVATE_KEY,FIREBASE_SDK_PRIVATE_KEY_ID,FIREBASE_SDK_PROJECT_ID,FIREBASE_SDK_TOKEN_URI,FIREBASE_SDK_TYPE"
          UPDATE_ENV_VARS_ARG=""

          # Construct the --update-env-vars argument
          IFS=',' read -ra ENV_VARS_ARRAY <<< "$ENV_VARS_LIST"
          for VAR_NAME in "${ENV_VARS_ARRAY[@]}"; do
            UPDATE_ENV_VARS_ARG+="$VAR_NAME=${!VAR_NAME},"
          done
          UPDATE_ENV_VARS_ARG=${UPDATE_ENV_VARS_ARG%}  # Remove trailing comma

          # Deploy get_all_conversations Cloud Function
          gcloud functions deploy get_all_conversations\
            --source=. \
            --runtime=python39 \
            --entry-point=get_all_conversations \
            --trigger-http \
            --allow-unauthenticated \
            --stage-bucket=firebase_code_bucket \
            --update-env-vars=$UPDATE_ENV_VARS_ARG
          
          # Deploy create_dummy_conversations Cloud Function
          gcloud functions deploy create_dummy_conversations\
            --source=. \
            --runtime=python39 \
            --entry-point=create_dummy_conversations \
            --trigger-http \
            --allow-unauthenticated \
            --stage-bucket=firebase_code_bucket \
            --update-env-vars=$UPDATE_ENV_VARS_ARG
          
          # Deploy update_conversation Cloud Function
          gcloud functions deploy update_conversation \
            --source=. \
            --runtime=python39 \
            --entry-point=update_conversation \
            --trigger-http \
            --allow-unauthenticated \
            --stage-bucket=firebase_code_bucket \
            --update-env-vars=$UPDATE_ENV_VARS_ARG

#      - name: Deploy get_all_conversations Cloud Function
#        run: |
#          gcloud functions deploy get_all_conversations\
#            --source=. \
#            --runtime=python39 \
#            --entry-point=get_all_conversations \
#            --trigger-http \
#            --allow-unauthenticated \
#            --stage-bucket=firebase_code_bucket \
#            --update-env-vars=GOOGLE_FUNCTION_TARGET=get_all_conversations
#
#      - name: Deploy create_dummy_conversations Cloud Function
#        run: |
#          gcloud functions deploy create_dummy_conversations\
#            --source=. \
#            --runtime=python39 \
#            --entry-point=create_dummy_conversations \
#            --trigger-http \
#            --allow-unauthenticated \
#            --stage-bucket=firebase_code_bucket \
#            --update-env-vars=GOOGLE_FUNCTION_TARGET=create_dummy_conversations,FIREBASE_SDK_TYPE=${{ secrets.FIREBASE_SDK_TYPE }},TEST_SECRET=${{ secrets.TEST_SECRET }}
#
#      - name: Deploy update_conversation Cloud Function
#        run: |
#          gcloud functions deploy update_conversation \
#            --source=. \
#            --runtime=python39 \
#            --entry-point=update_conversation \
#            --trigger-http \
#            --allow-unauthenticated \
#            --stage-bucket=firebase_code_bucket \
#            --update-env-vars=GOOGLE_FUNCTION_TARGET=update_conversation
