name: Deploy Cloud Function

on:
  push:
    branches:
      - main  # Adjust to your main branch name.

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SDK_TYPE: ${{ secrets.SDK_TYPE }}
      SDK_PROJECT_ID: ${{ secrets.SDK_PROJECT_ID }}
      SDK_PRIVATE_KEY_ID: ${{ secrets.SDK_PRIVATE_KEY_ID }}
      SDK_PRIVATE_KEY: ${{ secrets.SDK_PRIVATE_KEY }}
      SDK_CLIENT_EMAIL: ${{ secrets.SDK_CLIENT_EMAIL }}
      SDK_CLIENT_ID: ${{ secrets.SDK_CLIENT_ID }}
      SDK_CLIENT_X509_CERT_URL: ${{ secrets.SDK_CLIENT_X509_CERT_URL }}
      FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
      FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
      INSTAGRAM_EMAIL: ${{ secrets.INSTAGRAM_EMAIL }}
      INSTAGRAM_PASSWORD: ${{ secrets.INSTAGRAM_PASSWORD }}
      SEND_GMAIL_USERNAME: ${{ secrets.SEND_GMAIL_USERNAME }}
      SEND_GMAIL_APP_PASSWORD: ${{ secrets.SEND_GMAIL_APP_PASSWORD }}
      TEST_SECRET: ${{ secrets.TEST_SECRET }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          service_account_key: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      - name: Set env vars for Cloud Run deployment
        run: |# Create an array with all the environment variable assignments
          ENV_VARS_ARRAY=(
            "SDK_TYPE=${SDK_TYPE}"
            "SDK_PROJECT_ID=${SDK_PROJECT_ID}"
            "SDK_PRIVATE_KEY=${SDK_PRIVATE_KEY}"
            "SDK_PRIVATE_KEY_ID=${SDK_PRIVATE_KEY_ID}"
            "SDK_CLIENT_EMAIL=${SDK_CLIENT_EMAIL}"
            "SDK_CLIENT_ID=${SDK_CLIENT_ID}"
            "SDK_CLIENT_X509_CERT_URL=${SDK_CLIENT_X509_CERT_URL}"
            "FIREBASE_DATABASE_URL=${FIREBASE_DATABASE_URL}"
            "FIREBASE_API_KEY=${FIREBASE_API_KEY}"
            "INSTAGRAM_EMAIL=${INSTAGRAM_EMAIL}"
            "INSTAGRAM_PASSWORD=${INSTAGRAM_PASSWORD}"
            "SEND_GMAIL_USERNAME=${SEND_GMAIL_USERNAME}"
            "SEND_GMAIL_APP_PASSWORD=${SEND_GMAIL_APP_PASSWORD}"
          )

           # Join the array elements into a comma-separated string
          UPDATE_ENV_VARS_ARG=$(IFS=,; echo "${ENV_VARS_ARRAY[*]}")
          
          echo "UPDATE_ENV_VARS_ARG=$UPDATE_ENV_VARS_ARG" >> $GITHUB_ENV

      - name: Deploy get_all_conversations Cloud Function
        run: |
          echo "Deploying with env vars: $UPDATE_ENV_VARS_ARG"
          gcloud functions deploy get_all_conversations \
            --source=. \
            --runtime=python39 \
            --entry-point=get_all_conversations \
            --memory 128MB \
            --trigger-http \
            --allow-unauthenticated \
            --stage-bucket=firebase_code_bucket \
            --update-env-vars=$UPDATE_ENV_VARS_ARG

      - name: Deploy update_multiple_conversations Cloud Function
        run: |
          echo "Deploying with env vars: $UPDATE_ENV_VARS_ARG"
          gcloud functions deploy update_multiple_conversations \
            --source=. \
            --runtime=python39 \
            --entry-point=update_multiple_conversations \
            --memory 128MB \
            --trigger-http \
            --allow-unauthenticated \
            --stage-bucket=firebase_code_bucket \
            --update-env-vars=$UPDATE_ENV_VARS_ARG

      - name: Deploy create_order Cloud Function
        run: |
          echo "Deploying with env vars: $UPDATE_ENV_VARS_ARG"
          gcloud functions deploy create_order \
            --source=. \
            --runtime=python39 \
            --entry-point=create_order \
            --memory 128MB \
            --trigger-http \
            --allow-unauthenticated \
            --stage-bucket=firebase_code_bucket \
            --update-env-vars=$UPDATE_ENV_VARS_ARG

      - name: Deploy read_all_orders Cloud Function
        run: |
          echo "Deploying with env vars: $UPDATE_ENV_VARS_ARG"
          gcloud functions deploy read_all_orders \
            --source=. \
            --runtime=python39 \
            --entry-point=read_all_orders \
            --memory 128MB \
            --trigger-http \
            --allow-unauthenticated \
            --update-env-vars $UPDATE_ENV_VARS_ARG \
            --stage-bucket=firebase_code_bucket