name: Deploy Cloud Function

on:
  push:
    branches:
      - main  # Adjust to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.4.3
        with:
          project_id: omnichat-9a789
          service_account_key: {\n  \"type\": \"service_account\",\n  \"project_id\": \"omnichat-9a789\",\n  \"private_key_id\": \"5322d25ae6388962eb1841fbdb8e112b27066cc3\",\n  \"private_key\": \"-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDSMSyyUzcnajmL\nEcTzve6KU3989RRsMIGVsll86Kdy4bgiXF20fuEhY72QIE1VzoQt/sbCCTpRx9Yy\nvnkY6o8zMXXfEPeMFqUHdxuEC+SJK6dI6NdshTrJHWFcsxYxmx+4RmKOsMpmO9Eg\nls6ZpPYRCRDLwTkja08jXNJsQ3NgkiyF7p0SRPk0NbvDgc4dGbIrkNSZBEk/d6pc\nA8HhSNNd7xJqGfJ/FS4fK3KAsle2oWo8Emw/USmFMcOqNmePBN3sliMbtRMGD2RD\ngd06Bm8p0H/D8UvQvD6p7U4kelMtdgbf5A4MRpOxVIWQaGe27e3p0NDHCC91CsJg\nY3IpbyvpAgMBAAECggEAC8w7zISUN2+kbDRioCW8gmIeaUaeT1ZHp73bfQHYCEA4\nJCGYFt36R/P/u1u8y4CsdaJzyIdZEScM1EtRo77iq8ZubcdXhbLtr2YVkstSGArt\nuE9tbAdsXcZ65QeeSsmAtciploXAzo0z90bPsNsL/rfKDA275cuLpRn8K5x7mONx\ndu4dNj5Lp49VYyUKh2/BSv2ePneytDMZ85jOGNH4R+nb3h3pL52XY7dfYlHQua2i\nD9yiWHYL+Aq/Sbr8wT9R4XnhUkBU8WA+PMBS6lfR5AV4f0OcOyY7PjxU3QoWwcFO\nfI0jS/nRUkRkTStEwkU3P+zg7LSKaPxJSI79Im7AQQKBgQDolWUMjRBV8lz1CAiS\ncqoHpHMpipu2yCBmcjNF9Qf6SjyLiWEczgJNtFfEN7tGqXPmwIQLg+IhqL+5q8Px\nMeanD8njYS7o3CIl0cZl3ULpn1kINYi8Hm8YM8INUdu7cMuW87oLkHyo7/qwgFO1\nbdNv/0GYURMimSxI1230wevPOQKBgQDnWql/g75e21YVThPSuF60QPjEasxJrawW\n31uEwKX13KyFskig+QOioa7kw2+ZfXoVqhDZ9SJg1JD8N0kxw0+d6PVkkbtJMCR1\nY4frrSmrM7pYXK0laLVxlxTfOgn0ezVmFbzT88t/Oi9x7CpqJitVBSuJxmjqX5iV\nhb0bCg6SMQKBgQCu/C9BaSRANY9AfyHL5N8Nzukh+Pm8ZAcUbJks6fRtl8rDhMF+\npXPQOH3Lz85jlHvxwSfXbgsFHevZamSKI+wQBu3y15wub+h1IcWtv/FmyY93gKd2\nOUOGJvK5iLvT40IZORfhOXzAsYSfpHzWRGHOonIcgeruneVWjFZazkd26QKBgBzJ\nyEuovhiZnHWcOJVBAe/WId53F6KXbNGPy5iSTFRyuDkOvUDim5QyIEwxEYL8/SMS\n/XPRsAxyhvQLgR0jG5YfteFkzPRHfFHrJ6+o5YV7M1XpelYsWF+hGCTK2RBGAJgK\nXmvVa14ShHLdm02IIF48/XTwbn+zk44PjT9/Gd8RAoGAUZDbsy2KhfBDufhkG/oF\nhUpFCLsAjmVeWe1Gz7BrhRP4BdetyvcfV9IQLgL6n8WoBhVIkv2suiotiE2jHoEO\nEvUSGad9AyPGV+pVTDwtisTyuMCP++vEF7ucXD1hNfRNOwQbsGUDhw7kNR4dxT46\n+YG0YnJhze9tTJEzb4dKn5E=\n-----END PRIVATE KEY-----\n\",\n  \"client_email\": \"githubserviceaccount@omnichat-9a789.iam.gserviceaccount.com\",\n  \"client_id\": \"113181887301060638696\",\n  \"auth_uri\": \"https://accounts.google.com/o/oauth2/auth\",\n  \"token_uri\": \"https://oauth2.googleapis.com/token\",\n  \"auth_provider_x509_cert_url\": \"https://www.googleapis.com/oauth2/v1/certs\",\n  \"client_x509_cert_url\": \"https://www.googleapis.com/robot/v1/metadata/x509/githubserviceaccount%40omnichat-9a789.iam.gserviceaccount.com\",\n  \"universe_domain\": \"googleapis.com\"\n}\n
          export_default_credentials: true

      - name: Deploy Cloud Function
        run: |
          gcloud functions deploy get_all_conversations \
            --source=. \
            --runtime=python39 \
            --entry-point=get_all_conversations \
            --trigger-http \
            --allow-unauthenticated \
            --stage-bucket=firebase_code_bucket \
            --update-env-vars=GOOGLE_FUNCTION_TARGET=get_all_conversations
