name: Deploy Cloud Function

on:
  push:
    branches:
      - main  # Adjust to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
#    if: false  # Workflow will never run due to the condition
    env:
      FIREBASE_SDK_TYPE: ${{ secrets.FIREBASE_SDK_TYPE }}
      TEST_SECRET: ${{ secrets.TEST_SECRET }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          service_account_key: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      - name: Deploy get_all_conversations Cloud Function
        run: |
          gcloud functions deploy get_all_conversations \
            --source=. \
            --runtime=python39 \
            --entry-point=get_all_conversations \
            --trigger-http \
            --allow-unauthenticated \
            --stage-bucket=firebase_code_bucket \
            --update-env-vars=GOOGLE_FUNCTION_TARGET=get_all_conversations
